### ISSUE TITLE
Example of how to use extra_port_mappings?

### ISSUE THREAD

**Issue by nickjj** [kyma-incubator/terraform-provider-kind#46]
Hi,

I was looking at the resource documentation at https://github.com/kyma-incubator/terraform-provider-kind/blob/master/docs/resources/cluster.md but I didn't see a reference on how to use `extra_port_mappings`. I also didn't see any tests for this. I noticed that's the property name in the source code but I'm not well versed enough in Go in reverse what it expects as input.

I was trying to convert this `kind.yaml` config to TF using your provider:

```yml
nodes:
- role: "control-plane"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
  - containerPort: 443
    hostPort: 443
```

So far this is what I have:

```tf
node {
  role = "control-plane"
  extra_port_mappings = ??
}
```

Any suggestions?

**Edit:**

After a bit of tinkering this partially works:

```tf
      extra_port_mappings {
        container_port = 80
        host_port      = 80
      }
```

It passes the `validate` command but I don't see a path forward on how to define multiple ports (80 and 443) since it doesn't support setting `[80, 443]` as a value or defining the same `container_port` property twice.
